version: 2.1

commands:
  build:
    steps:
      - checkout
      - run: pip3 install --editable ."[doc]"
      - run: pip3 install pytest-cov codecov
  unittest:
    steps:
      - run: pytest --capture=no --verbose --cov=icepack
  realtest:
    steps:
      - run: cp ~/registry-nsidc.txt ~/icepack/icepack/
      - run: jupyter nbconvert --to notebook --execute notebooks/tutorials/03-larsen-ice-shelf.ipynb
  codecov:
    steps:
      - run: codecov

jobs:
  python36:
    docker:
      - image: icepack/firedrake-python3.6:0.5.0
    working_directory: ~/icepack
    steps:
      - build
      - unittest
      - realtest
  python38:
    docker:
      - image: icepack/firedrake-python3.8:0.5.0
    working_directory: ~/icepack
    steps:
      - build
      - unittest
      - codecov
      - realtest

workflows:
  version: 2
  tests:
    jobs:
      - python36
      - python38
