name: 'Build and test icepack'
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        version: [2026.4.2, dev-release]
    runs-on: ubuntu-latest
    container:
      image: docker.io/firedrakeproject/firedrake-vanilla-default:${{ matrix.version }}
      options: --user root
    steps:
      - name: Install dependences
        run: |
          apt update
          apt install -yq libglu1-mesa-dev libxft2-dev
          python3 -m pip install jupyter ipykernel nbconvert
      - name: Check out git repository
        uses: actions/checkout@v5
      - name: Install package
        run: |
          python3 -m ipykernel install --user --name=firedrake
          python3 -m pip install --editable ".[pygmsh]"
      - name: Run unit tests
        run: pytest
      - name: Run example notebooks
        run: |
          jupyter nbconvert --to notebook --execute notebooks/tutorials/02-synthetic-ice-shelf.ipynb
          jupyter nbconvert --to notebook --execute notebooks/how-to/01-performance.ipynb
          jupyter nbconvert --to notebook --execute notebooks/how-to/02-checkpointing.ipynb
          jupyter nbconvert --to notebook --execute notebooks/how-to/03-adaptivity.ipynb
